name: Lint & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-test:
    name: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout template-commons
        uses: actions/checkout@v4
        with:
          repository: KooshaPari/template-commons
          path: template-commons

      - uses: KooshaPari/phenotypeActions/actions/lint-test@main
