name: Security Guard

on:
  workflow_call:
    secrets:
      GITGUARDIAN_API_KEY:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ggshield-scan:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - actions/setup-python@c8813ba1bc76ebf779b911ad8ffccbf2e449cb48
        with:
          python-version: "3.13"
      - name: Install ggshield
        run: pip install ggshield==1.38.0
      - name: Run ggshield secret scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield secret scan path . --recursive
